[profile.default]
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 2
  out = "out"
  solc_version = "0.8.30"
  src = "src"
  viaIR = true

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 120
  multiline_func_header = "attributes_first"
  number_underscore = "preserve"
  quote_style = "double"
  single_line_statement_blocks = "single"
  tab_width = 2
  wrap_comments = true

[rpc_endpoints]
  arbitrum = "${ARBITRUM_MAINNET_RPC}"
  base = "${BASE_MAINNET_RPC}"
  hyperevm = "${HYPEREVM_MAINNET_RPC}"
